In [16]:
import sys
sys.path.append(r"C:\Users\hrida\ReinforcementLearning")
from Environments import initialize_gridWorld as gridWorld 
from GridWorldActions import action_tuple, actions
import copy
import numpy as np

In [17]:
action_space, state_space, rewards = gridWorld()

In [18]:
new_state_space = copy.deepcopy(state_space)

In [19]:
action_visualize = copy.deepcopy(state_space)

In [20]:
rewards

array([[-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., -1.],
       [-1., -1., -1., 10.]])

In [21]:
ROWS = len(state_space)
COLS = len(state_space[0])

In [22]:
#pi(a|s) * (r + gamma * v(next_state))

In [23]:
def policy_iteration(row, col, gamma=0.9):
    summ = 0
    for action in action_space:
        next_state = action_tuple(row, col, action)
        reward = rewards[next_state]
        next_state_value = state_space[next_state]
        net = reward + gamma * next_state_value
        summ += net
    return summ/len(action_space)

In [25]:
for runs in range(10000):
    if runs%1000==0:
        print(runs)
    for rows in range(ROWS):
        for cols in range(COLS):
            current_state_value = state_space[rows,cols]
            current_row = rows
            current_col = cols
            new_state_space[int(current_row), int(current_col)] = policy_iteration(int(current_row), int(current_col))
    if state_space - new_state_space < 0.0001:
        print(runs)
        break
    state_space = new_state_space

0


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
state_space

array([[-7.82456122, -7.34113038, -6.51087033, -5.74579832],
       [-7.34113038, -6.50623976, -4.89495798, -3.08997001],
       [-6.51087033, -4.89495798, -1.20384427,  4.44197072],
       [-5.74579832, -3.08997001,  4.44197072, 11.81615786]])

In [13]:
for rows in range(ROWS):
    for cols in range(COLS):
        max_list=[]
        current_row = rows
        current_col = cols
        for action in action_space:
            max_list.append(actions(current_row, current_col, action, state_space))
        index= max_list.index(max(max_list))
        action_visualize[current_row, current_col] = index
            

In [15]:
"""
We can see the greedy action to be taken for each state. 

0 -> Left
1 ->Right
2 ->Upwards
3 ->Downwards


"""
action_visualize

array([[3., 3., 3., 3.],
       [1., 1., 3., 3.],
       [1., 1., 1., 3.],
       [1., 1., 1., 0.]])