In [43]:
import numpy as np
import pandas as pd
import random

In [2]:
"""
Making a Randomwalk Environment with 2n+1 states.

0l . . . 0 0 0 0 0 0 0 0 S 0 0 0 0 0 0 0 0 . . . 0r

0l and 0r denote the terminal states.

Action Space :

-1 (Left)
+1 (Right)

Rewards Setting :

-1 : Agent goes to 0l
+1 : Agent goes to 0r
0 : Intermediary States

"""

'\nMaking a Randomwalk Environment with 2n+1 states. \n\n0l . . . 0 0 0 0 0 0 0 0 S 0 0 0 0 0 0 0 0 . . . 0r\n\n0l and 0r denote the terminal states. \n\nAction Space : \n\n0 (Left) \n1 (Right)\n\nRewards Setting : \n\n-1 : Agent goes to 0l\n+1 : Agent goes to 0r\n0 : Intermediary States\n\n'

In [87]:
def initialize_env(states=19):
  STATES = states
  value_list = np.zeros(STATES)
  state_check = np.zeros(STATES)
  rewards = np.zeros(STATES)
  rewards[0] = -1
  rewards[STATES-1] = 1
  start_pos = (STATES+1)/2 -1
  action_space = [-1, 1]
  return value_list, state_check, int(start_pos), rewards, action_space

In [88]:
def action(action_space = a):
  return random.choice(action_space)

In [89]:
#TD Update v[ith] = v[ith] + alpha * (reward + gamma * v[ith+1] - v[ith]) for non terminal
#TD Update v[ith] = v[ith] + alpha * (reward - [vith])

In [124]:
v, s, pos, r, a = initialize_env()

In [125]:
v

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [126]:
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.])

In [127]:
r

array([-1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  1.])

In [128]:
pos

9

In [130]:
def isTerminal (current_state, STATES):
  if current_state ==0 or current_state == STATES -1:
    return True
  return False

def step (current_state, action, rewards, STATES) :
  action = action
  next_state = current_state + action
  reward = rewards[next_state]
  isT = isTerminal (current_state, STATES)
  return next_state, reward

def calc_TD_nonT(current_state, next_state, reward, alpha, gamma, value_list):
  value_list[current_state] += alpha * (reward + gamma * (value_list[next_state]) - value_list[current_state])
  return value_list

def calc_TD_T(current_state, reward, alpha, gamma, value_list):
  value_list[current_state] += alpha * (reward - value_list[current_state])
  return value_list

In [131]:
alpha = 0.001
gamma = 0.10
isT = False
steps=0

In [132]:
def run():
  while isT != True:
    next_state, reward= step(pos, action(), r, 19)
    isT = isTerminal(next_state, 19)
    if isT == True:
      print(f"This is the terminal state - {next_state}")
      print(f"The reward is {reward}")
      v = calc_TD_T (pos, reward, alpha, gamma, v)
      print ("The episode has ended here")
      break
    else:
      print(f"The next state is {next_state}")
      print(f"The reward obtained is {reward}")
      v= calc_TD_nonT(pos, next_state, reward, alpha, gamma, v)
      pos = next_state
  return v

The next state is 8
The reward obtained is 0.0
The next state is 9
The reward obtained is 0.0
The next state is 10
The reward obtained is 0.0
The next state is 9
The reward obtained is 0.0
The next state is 10
The reward obtained is 0.0
The next state is 11
The reward obtained is 0.0
The next state is 12
The reward obtained is 0.0
The next state is 11
The reward obtained is 0.0
The next state is 12
The reward obtained is 0.0
The next state is 11
The reward obtained is 0.0
The next state is 10
The reward obtained is 0.0
The next state is 9
The reward obtained is 0.0
The next state is 8
The reward obtained is 0.0
The next state is 9
The reward obtained is 0.0
The next state is 8
The reward obtained is 0.0
The next state is 7
The reward obtained is 0.0
The next state is 8
The reward obtained is 0.0
The next state is 7
The reward obtained is 0.0
The next state is 6
The reward obtained is 0.0
The next state is 5
The reward obtained is 0.0
The next state is 6
The reward obtained is 0.0
The n

In [133]:
v

array([ 0.   , -0.001,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,
        0.   ,  0.   ,  0.   ])